@rootURL = http://localhost:5167

GET {{rootURL}}/api/product
Accept: application/json

###
GET {{rootURL}}/api/product/3
Accept: application/json

###
POST {{rootURL}}/api/product
Content-Type: application/json
{
  "Name": "IPhone", 
  "TagIds": [2, 3],
  "CategoryId": 1, 
  "Price": 1000,
  "ProductSeo": {
    "MetaTitle": "IPhone 15 Pro Max - Best Deal",
    "MetaDescription": "Buy the latest IPhone at the best price.",
    "Slug": "iphone-15-pro-max",
    "OpenGraphImageUrl": "https://example.com/iphone.jpg"
  }
}

###
PUT {{rootURL}}/api/product/3
Content-Type: application/json
{
  "TagIds": [3],
  "ProductSeo": {
    "MetaTitle": "IPhone 15 Pro Max - Best Deal",
    "MetaDescription": "Buy the latest IPhone at the best price.",
    "Slug": "iphone-15-pro-max",
    "OpenGraphImageUrl": "https://example.com/iphone.jpg"
  }
}

###
DELETE {{rootURL}}/api/product/10