name: .NET Web APP CI/CD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore dependencies
      run: dotnet restore StoreApi.sln

    - name: Build
      run: dotnet build StoreApi.sln --no-restore --configuration Release

    - name: Unit Tests
      run: dotnet test Tests/UnitTests/UnitTests.csproj --no-build --configuration Release --verbosity normal

    - name: Integration Tests
      run: dotnet test Tests/IntegrationTests/IntegrationTests.csproj --no-build --configuration Release --verbosity normal


  deploy-to-container-apps:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/azure/migration')
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.STOREAPICONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STOREAPICONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STOREAPICONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: StoreApi/Dockerfile
          registryUrl: storeacrkv.azurecr.io
          registryUsername: ${{ secrets.STOREAPICONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STOREAPICONTAINER_REGISTRY_PASSWORD }}
          containerAppName: store-api-container
          resourceGroup: store-rg
          imageToBuild: storeacrkv.azurecr.io/store-api-container:${{ github.sha }}
