name: .NET Web APP CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"

    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Restore dependencies
      run: dotnet restore StoreApi.sln

    - name: Build
      run: dotnet build StoreApi.sln --no-restore --configuration Release

    - name: Unit Tests
      run: dotnet test Tests/UnitTests/UnitTests.csproj --no-build --configuration Release --verbosity normal

    - name: Integration Tests
      run: dotnet test Tests/IntegrationTests/IntegrationTests.csproj --no-build --configuration Release --verbosity normal

    - name: Publish Artifact
      run: dotnet publish StoreApi/StoreApi.csproj --no-build --configuration Release --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-api-drop
        path: ./backend/publish